// Accentual-syllabic versification poems, syllabified for the scansion-authoring viewer.
window.VERSE_POEMS = [
  { id: "royal", poet: "Wyatt", src: "They Flee from Me (rhyme royal)", lines: [
    { syl: ["They","flee","from","me","that","some","time","did","me","seek"], sp: [false,true,true,true,true,true,false,true,true,true] },
    { syl: ["With","na","ked","foot,","stalk","ing","in","my","cham","ber."], sp: [false,true,false,true,true,false,true,true,true,false] },
    { syl: ["I","have","seen","them","gen","tle,","tame,","and","meek,"], sp: [false,true,true,true,true,false,true,true,true] },
    { syl: ["That","now","are","wild","and","do","not","re","mem","ber"], sp: [false,true,true,true,true,true,true,true,false,false] },
    { syl: ["That","some","time","they","put","them","selves","in","dan","ger"], sp: [false,true,false,true,true,true,false,true,true,false] },
    { syl: ["To","take","bread","at","my","hand;","and","now","they","range,"], sp: [false,true,true,true,true,true,true,true,true,true] },
    { syl: ["Bus","i","ly","seek","ing","with","a","con","tin","ual","change."], sp: [false,false,false,true,false,true,true,true,false,false,true] },
    { syl: ["Thanked","be","for","tune","it","hath","been","o","ther","wise"], sp: [false,true,true,false,true,true,true,true,false,false] },
    { syl: ["Twen","ty","times","bet","ter;","but","once","in","spe","cial,"], sp: [false,false,true,true,false,true,true,true,true,false] },
    { syl: ["In","thin","ar","ray","af","ter","a","plea","sant","guise,"], sp: [false,true,true,false,true,false,true,true,false,true] },
    { syl: ["When","her","loose","gown","from","her","shoul","ders","did","fall,"], sp: [false,true,true,true,true,true,true,false,true,true] },
    { syl: ["And","she","me","caught","in","her","arms","long","and","small;"], sp: [false,true,true,true,true,true,true,true,true,true] },
    { syl: ["There","with","all","sweet","ly","did","me","kiss,"], sp: [false,false,false,true,false,true,true,true] },
    { syl: ["And","soft","ly","said,","“Dear","heart,","how","like","you","this?”"], sp: [false,true,false,true,true,true,true,true,true,true] }
  ] },
  { id: "pet1", poet: "Wyatt", src: "Whoso List to Hunt", lines: [
    { syl: ["Who","so","list","to","hunt,","I","know","where","is","an","hind,"], sp: [false,false,true,true,true,true,true,true,true,true,true] },
    { syl: ["But","as","for","me,","hé","las,","I","may","no","more."], sp: [false,true,true,true,true,false,true,true,true,true] },
    { syl: ["The","vain","tra","vail","hath","wea","ried","me","so","sore,"], sp: [false,true,true,false,true,true,false,true,true,true] },
    { syl: ["I","am","of","them","that","far","thest","com","eth","be","hind."], sp: [false,true,true,true,true,true,false,true,false,true,false] },
    { syl: ["Yet","may","I","by","no","means","my","wea","ried","mind"], sp: [false,true,true,true,true,true,true,true,false,true] },
    { syl: ["Draw","from","the","deer,","but","as","she","fleeth","a","fore"], sp: [false,true,true,true,true,true,true,true,true,false] },
    { syl: ["Faint","ing","I","fol","low.","I","leave","off","there","fore,"], sp: [false,false,true,true,false,true,true,true,true,false] },
    { syl: ["Sith","ens","in","a","net","I","seek","to","hold","the","wind."], sp: [false,false,true,true,true,true,true,true,true,true,true] },
    { syl: ["Who","list","her","hunt,","I","put","him","out","of","doubt,"], sp: [false,true,true,true,true,true,true,true,true,true] },
    { syl: ["As","well","as","I","may","spend","his","time","in","vain."], sp: [false,true,true,true,true,true,true,true,true,true] },
    { syl: ["And","grav","en","with","dia","monds","in","let","ters","plain"], sp: [false,true,false,true,true,false,true,true,false,true] },
    { syl: ["There","is","writ","ten,","her","fair","neck","round","a","bout:"], sp: [false,true,true,false,true,true,true,true,true,false] },
    { syl: ["“No","li","me","tan","ge","re,","for","Cae","sar's","I","am,"], sp: [false,false,true,true,false,false,true,true,false,true,true] },
    { syl: ["And","wild","for","to","hold,","though","I","seem","tame.”"], sp: [false,true,true,true,true,true,true,true,true] }
  ] },
  { id: "spen", poet: "Spenser", src: "Amoretti 75", lines: [
    { syl: ["One","day","I","wrote","her","name","up","on","the","strand,"], sp: [false,true,true,true,true,true,true,false,true,true] },
    { syl: ["But","came","the","waves","and","wash","èd","it","a","way:"], sp: [false,true,true,true,true,true,false,true,true,false] },
    { syl: ["A","gain","I","wrote","it","with","a","sec","ond","hand,"], sp: [false,false,true,true,true,true,true,true,false,true] },
    { syl: ["But","came","the","tide,","and","made","my","pains","his","prey."], sp: [false,true,true,true,true,true,true,true,true,true] },
    { syl: ["“Vain","man,”","said","she,","“that","dost","in","vain","as","say"], sp: [false,true,true,true,true,true,true,true,true,false] },
    { syl: ["A","mor","tal","thing","so","to","im","mor","tal","ize;"], sp: [false,true,false,true,true,true,true,false,false,false] },
    { syl: ["For","I","my","self","shall","like","to","this","de","cay,"], sp: [false,true,true,false,true,true,true,true,true,false] },
    { syl: ["And","eek","my","name","be","wip","èd","out","like","wise.”"], sp: [false,true,true,true,true,true,false,true,true,false] },
    { syl: ["“Not","so,”","quod","I,","“let","bas","er","things","de","vise"], sp: [false,true,true,true,true,true,false,true,true,false] },
    { syl: ["To","die","in","dust,","but","you","shall","live","by","fame:"], sp: [false,true,true,true,true,true,true,true,true,true] },
    { syl: ["My","verse","your","vir","tues","rare","shall","e","ter","nize,"], sp: [false,true,true,true,false,true,true,true,false,false] },
    { syl: ["And","in","the","heav","ens","write","your","glo","rious","name:"], sp: [false,true,true,true,false,true,true,true,false,true] },
    { syl: ["Where","when","as","Death","shall","all","the","world","sub","due,"], sp: [false,true,false,true,true,true,true,true,true,false] },
    { syl: ["Our","love","shall","live,","and","lat","er","life","re","new."], sp: [false,true,true,true,true,true,false,true,true,false] }
  ] },
  { id: "shak", poet: "Shakespeare", src: "Sonnet 18", lines: [
    { syl: ["Shall","I","com","pare","thee","to","a","sum","mer’s","day?"], sp: [false,true,true,false,true,true,true,true,false,true] },
    { syl: ["Thou","art","more","love","ly","and","more","tem","per","ate:"], sp: [false,true,true,true,false,true,true,true,false,false] },
    { syl: ["Rough","winds","do","shake","the","dar","ling","buds","of","May,"], sp: [false,true,true,true,true,true,false,true,true,true] },
    { syl: ["And","sum","mer’s","lease","hath","all","too","short","a","date;"], sp: [false,true,false,true,true,true,true,true,true,true] },
    { syl: ["Some","time","too","hot","the","eye","of","heav","en","shines,"], sp: [false,false,true,true,true,true,true,true,false,true] },
    { syl: ["And","of","ten","is","his","gold","com","plex","ion","dimm’d;"], sp: [false,true,false,true,true,true,true,false,false,true] },
    { syl: ["And","ev","’ry","fair","from","fair","some","time","de","clines,"], sp: [false,true,false,true,true,true,true,false,true,false] },
    { syl: ["By","chance","or","na","ture’s","chang","ing","course","un","trimm’d;"], sp: [false,true,true,true,false,true,false,true,true,false] },
    { syl: ["But","thy","e","ter","nal","sum","mer","shall","not","fade,"], sp: [false,true,true,false,false,true,false,true,true,true] },
    { syl: ["Nor","lose","pos","ses","sion","of","that","fair","thou","ow’st;"], sp: [false,true,true,false,false,true,true,true,true,true] },
    { syl: ["Nor","shall","Death","brag","thou","wan","der’st","in","his","shade,"], sp: [false,true,true,true,true,true,false,true,true,true] },
    { syl: ["When","in","e","ter","nal","lines","to","time","thou","grow’st:"], sp: [false,true,true,false,false,true,true,true,true,true] },
    { syl: ["So","long","as","men","can","breathe","or","eyes","can","see,"], sp: [false,true,true,true,true,true,true,true,true,true] },
    { syl: ["So","long","lives","this,","and","this","gives","life","to","thee."], sp: [false,true,true,true,true,true,true,true,true,true] }
  ] },
  { id: "marlowe", poet: "Marlowe", src: "Doctor Faustus", lines: [
    { syl: ["Was","this","the","face","that","launch’d","a","thou","sand","ships,"], sp: [false,true,true,true,true,true,true,true,false,true] },
    { syl: ["And","burnt","the","top","less","tow’rs","of","Il","i","um?"], sp: [false,true,true,true,false,true,true,true,false,false] },
    { syl: ["Sweet","Hel","en,","make","me","im","mor","tal","with","a","kiss."], sp: [false,true,false,true,true,true,false,false,true,true,true] },
    { syl: ["Her","lips","suck","forth","my","soul:","see,","where","it","flies!"], sp: [false,true,true,true,true,true,true,true,true,true] },
    { syl: ["Come,","Hel","en,","come,","give","me","my","soul","a","gain."], sp: [false,true,false,true,true,true,true,true,true,false] },
    { syl: ["Here","will","I","dwell,","for","heav’n","is","in","these","lips,"], sp: [false,true,true,true,true,true,true,true,true,true] },
    { syl: ["And","all","is","dross","that","is","not","Hel","e","na."], sp: [false,true,true,true,true,true,true,true,false,false] },
    { syl: ["I","will","be","Par","is,","and","for","love","of","thee,"], sp: [false,true,true,true,false,true,true,true,true,true] },
    { syl: ["In","stead","of","Troy,","shall","Wit","ten","berg","be","sack’d…"], sp: [false,false,true,true,true,true,false,false,true,true] }
  ] },
  { id: "fq", poet: "Spenser", src: "The Faerie Queene I.i.1", lines: [
    { syl: ["A","Gen","tle","Knight","was","prick","ing","on","the","plaine,"], sp: [false,true,false,true,true,true,false,true,true,true] },
    { syl: ["Y","cladd","in","migh","tie","armes","and","sil","ver","shielde,"], sp: [false,false,true,true,false,true,true,true,false,true] },
    { syl: ["Where","in","old","dints","of","deepe","wounds","did","re","maine,"], sp: [false,false,true,true,true,true,true,true,true,false] },
    { syl: ["The","cru","ell","markes","of","man","y","a","blood","y","fielde;"], sp: [false,true,false,true,true,true,false,true,true,false,true] },
    { syl: ["Yet","armes","till","that","time","did","he","nev","er","wield:"], sp: [false,true,true,true,true,true,true,true,false,true] },
    { syl: ["His","an","gry","steede","did","chide","his","fom","ing","bitt,"], sp: [false,true,false,true,true,true,true,true,false,true] },
    { syl: ["As","much","dis","day","ning","to","the","curbe","to","yield:"], sp: [false,true,true,false,false,true,true,true,true,true] },
    { syl: ["Full","jol","ly","knight","he","seemd,","and","faire","did","sitt,"], sp: [false,true,false,true,true,true,true,true,true,true] },
    { syl: ["As","one","for","knight","ly","giusts","and","fierce","en","coun","ters","fitt."], sp: [false,true,true,true,false,true,true,true,true,false,false,true] }
  ] },
  { id: "skelton", poet: "Skelton", src: "Colin Clout", lines: [
    { syl: ["For","though","my","rhyme","be","rag","ged,"], sp: [false,true,true,true,true,true,false] },
    { syl: ["Tat","tered","and","jag","ged,"], sp: [false,false,true,true,false] },
    { syl: ["Rude","ly","rain-","beat","en,"], sp: [false,false,true,true,false] },
    { syl: ["Rust","y","and","moth-","eat","en,"], sp: [false,false,true,true,true,false] },
    { syl: ["If","ye","take","well","there","with,"], sp: [false,true,true,true,true,false] },
    { syl: ["It","hath","in","it","some","pith."], sp: [false,true,true,true,true,true] }
  ] },
  { id: "donne", poet: "Donne", src: "Batter my heart", lines: [
    { syl: ["Bat","ter","my","heart,","three-","per","son’d","God;","for","you"], sp: [false,false,true,true,true,true,false,true,true,true] },
    { syl: ["As","yet","but","knock,","breathe,","shine,","and","seek","to","mend;"], sp: [false,true,true,true,true,true,true,true,true,true] },
    { syl: ["That","I","may","rise,","and","stand,","o’er","throw","me,","and","bend"], sp: [false,true,true,true,true,true,true,false,true,true,true] },
    { syl: ["Your","force,","to","break,","blow,","burn,","and","make","me","new."], sp: [false,true,true,true,true,true,true,true,true,true] },
    { syl: ["I,","like","an","u","surp’d","town,","to","an","oth","er","due,"], sp: [false,true,true,true,false,true,true,true,false,false,true] },
    { syl: ["La","bour","to","ad","mit","you,","but","Oh,","to","no","end."], sp: [false,false,true,true,false,true,true,true,true,true,true] },
    { syl: ["Rea","son,","your","vice","roy","in","me,","me","should","de","fend,"], sp: [false,false,true,true,false,true,true,true,true,true,false] },
    { syl: ["But","is","cap","tiv’d,","and","proves","weak","or","un","true."], sp: [false,true,true,false,true,true,true,true,true,false] },
    { syl: ["Yet","dear","ly","I","love","you,","and","would","be","lov’d","fain,"], sp: [false,true,false,true,true,true,true,true,true,true,true] },
    { syl: ["But","am","be","troth’d","un","to","your","en","e","my:"], sp: [false,true,true,false,true,false,true,true,false,false] },
    { syl: ["Di","vorce","me,","un","tie,","or","break","that","knot","a","gain,"], sp: [false,false,true,true,false,true,true,true,true,true,false] },
    { syl: ["Take","me","to","you,","im","pris","on","me,","for","I,"], sp: [false,true,true,true,true,false,false,true,true,true] },
    { syl: ["Ex","cept","you","en","thrall","me,","nev","er","shall","be","free,"], sp: [false,false,true,true,false,true,true,false,true,true,true] },
    { syl: ["Nor","ev","er","chaste,","ex","cept","you","rav","ish","me."], sp: [false,true,false,true,true,false,true,true,false,true] }
  ] },
  { id: "milton", poet: "Milton", src: "Paradise Lost 1.1–10", lines: [
    { syl: ["Of","Man’s","first","dis","o","be","dience,","and","the","fruit"], sp: [false,true,true,true,false,false,false,true,true,true] },
    { syl: ["Of","that","for","bid","den","tree","whose","mor","tal","taste"], sp: [false,true,true,false,false,true,true,true,false,true] },
    { syl: ["Brought","death","in","to","the","world,","and","all","our","woe,"], sp: [false,true,true,false,true,true,true,true,true,true] },
    { syl: ["With","loss","of","E","den,","till","one","great","er","Man"], sp: [false,true,true,true,false,true,true,true,false,true] },
    { syl: ["Re","store","us,","and","re","gain","the","bliss","ful","seat,"], sp: [false,false,true,true,true,false,true,true,false,true] },
    { syl: ["Sing,","Heav’n","ly","Muse,","that","on","the","se","cret","top"], sp: [false,true,false,true,true,true,true,true,false,true] },
    { syl: ["Of","O","reb,","or","of","Si","nai,","didst","in","spire"], sp: [false,true,false,true,true,true,false,true,true,false] },
    { syl: ["That","shep","herd","who","first","taught","the","cho","sen","seed"], sp: [false,true,false,true,true,true,true,true,false,true] },
    { syl: ["In","the","be","gin","ning","how","the","heav’ns","and","earth"], sp: [false,true,true,false,false,true,true,true,true,true] },
    { syl: ["Rose","out","of","Cha","os…"], sp: [false,true,true,true,false] }
  ] },
  { id: "couplet", poet: "Pope", src: "An Essay on Criticism", lines: [
    { syl: ["A","lit","tle","learn","ing","is","a","dan","g’rous","thing;"], sp: [false,true,false,true,false,true,true,true,false,true] },
    { syl: ["Drink","deep,","or","taste","not","the","Pi","e","rian","spring:"], sp: [false,true,true,true,true,true,true,false,false,true] },
    { syl: ["There","shal","low","draughts","in","tox","i","cate","the","brain,"], sp: [false,true,false,true,true,false,false,false,true,true] },
    { syl: ["And","drink","ing","large","ly","so","bers","us","a","gain."], sp: [false,true,false,true,false,true,false,true,true,false] },
    { syl: ["Fired","at","first","sight","with","what","the","Muse","im","parts,"], sp: [false,true,true,true,true,true,true,true,true,false] },
    { syl: ["In","fear","less","youth","we","tempt","the","heights","of","Arts,"], sp: [false,true,false,true,true,true,true,true,true,true] },
    { syl: ["While","from","the","bound","ed","lev","el","of","our","mind"], sp: [false,true,true,true,false,true,false,true,true,true] },
    { syl: ["Short","views","we","take,","nor","see","the","lengths","be","hind;"], sp: [false,true,true,true,true,true,true,true,true,false] },
    { syl: ["But","more","ad","vanced,","be","hold","with","strange","sur","prise"], sp: [false,true,true,false,true,false,true,true,true,false] },
    { syl: ["New","dis","tant","scenes","of","end","less","sci","ence","rise!"], sp: [false,true,false,true,true,true,false,true,false,true] }
  ] },
  { id: "elegy", poet: "Gray", src: "Elegy Written in a Country Churchyard", lines: [
    { syl: ["The","cur","few","tolls","the","knell","of","part","ing","day,"], sp: [false,true,false,true,true,true,true,true,false,true] },
    { syl: ["The","low","ing","herd","wind","slow","ly","o’er","the","lea,"], sp: [false,true,false,true,true,true,false,true,true,true] },
    { syl: ["The","plow","man","home","ward","plods","his","wea","ry","way,"], sp: [false,true,false,true,false,true,true,true,false,true] },
    { syl: ["And","leaves","the","world","to","dark","ness","and","to","me."], sp: [false,true,true,true,true,true,false,true,true,true] },
    { syl: ["Now","fades","the","glim","m’ring","land","scape","on","the","sight,"], sp: [false,true,true,true,false,true,false,true,true,true] },
    { syl: ["And","all","the","air","a","sol","emn","still","ness","holds,"], sp: [false,true,true,true,true,true,false,true,false,true] },
    { syl: ["Save","where","the","bee","tle","wheels","his","dron","ing","flight,"], sp: [false,true,true,true,false,true,true,true,false,true] },
    { syl: ["And","drow","sy","tink","lings","lull","the","dis","tant","folds…"], sp: [false,true,false,true,false,true,true,true,false,true] }
  ] },
  { id: "ode", poet: "Keats", src: "Ode to a Nightingale", lines: [
    { syl: ["My","heart","aches,","and","a","drow","sy","numb","ness","pains"], sp: [false,true,true,true,true,true,false,true,false,true] },
    { syl: ["My","sense,","as","though","of","hem","lock","I","had","drunk,"], sp: [false,true,true,true,true,true,false,true,true,true] },
    { syl: ["Or","emp","tied","some","dull","o","piate","to","the","drains"], sp: [false,true,false,true,true,true,false,true,true,true] },
    { syl: ["One","min","ute","past,","and","Le","the-","wards","had","sunk:"], sp: [false,true,false,true,true,true,false,false,true,true] },
    { syl: ["’Tis","not","through","en","vy","of","thy","hap","py","lot,"], sp: [false,true,true,true,false,true,true,true,false,true] },
    { syl: ["But","be","ing","too","hap","py","in","thine","hap","pi","ness,—"], sp: [false,true,false,true,true,false,true,true,true,false,false] },
    { syl: ["That","thou,","light-","wing","èd","Dry","ad","of","the","trees,"], sp: [false,true,true,true,false,true,false,true,true,true] },
    { syl: ["In","some","me","lo","dious","plot"], sp: [false,true,true,false,false,true] },
    { syl: ["Of","beech","en","green,","and","shad","ows","num","ber","less,"], sp: [false,true,false,true,true,true,false,true,false,false] },
    { syl: ["Sing","est","of","sum","mer","in","full-","throat","ed","ease."], sp: [false,false,true,true,false,true,true,true,false,true] }
  ] },
  { id: "terza", poet: "Shelley", src: "Ode to the West Wind I", lines: [
    { syl: ["O","wild","West","Wind,","thou","breath","of","Au","tumn’s","be","ing,"], sp: [false,true,true,true,true,true,true,true,false,true,false] },
    { syl: ["Thou,","from","whose","un","seen","pres","ence","the","leaves","dead"], sp: [false,true,true,true,false,true,false,true,true,true] },
    { syl: ["Are","driv’n,","like","ghosts","from","an","en","chant","er","flee","ing,"], sp: [false,true,true,true,true,true,true,false,false,true,false] },
    { syl: ["Yel","low,","and","black,","and","pale,","and","hec","tic","red,"], sp: [false,false,true,true,true,true,true,true,false,true] },
    { syl: ["Pes","ti","lence-","strick","en","mul","ti","tudes:","O","thou,"], sp: [false,false,false,true,false,true,false,false,true,true] },
    { syl: ["Who","char","io","test","to","their","dark","win","try","bed"], sp: [false,true,false,false,true,true,true,true,false,true] },
    { syl: ["The","wing","èd","seeds,","where","they","lie","cold","and","low,"], sp: [false,true,false,true,true,true,true,true,true,true] },
    { syl: ["Each","like","a","corpse","with","in","its","grave,","un","til"], sp: [false,true,true,true,true,false,true,true,true,false] },
    { syl: ["Thine","az","ure","sis","ter","of","the","Spring","shall","blow"], sp: [false,true,false,true,false,true,true,true,true,true] },
    { syl: ["Her","clar","ion","o’er","the","dream","ing","earth,","and","fill"], sp: [false,true,false,true,true,true,false,true,true,true] },
    { syl: ["(Driv","ing","sweet","buds","like","flocks","to","feed","in","air)"], sp: [false,false,true,true,true,true,true,true,true,true] },
    { syl: ["With","liv","ing","hues","and","o","dours","plain","and","hill:"], sp: [false,true,false,true,true,true,false,true,true,true] },
    { syl: ["Wild","Spir","it,","which","art","mov","ing","ev","ery","where;"], sp: [false,true,false,true,true,true,false,true,false,false] },
    { syl: ["De","stroy","er","and","pre","serv","er;","hear,","oh","hear!"], sp: [false,false,false,true,true,false,false,true,true,true] }
  ] },
  { id: "ballad", poet: "Anon.", src: "Sir Patrick Spens", lines: [
    { syl: ["The","king","sits","in","Dum","fer","ling","toune,"], sp: [false,true,true,true,true,false,false,true] },
    { syl: ["Drink","ing","the","blude-","reid","wine:"], sp: [false,false,true,true,true,true] },
    { syl: ["“O","whar","will","I","get","guid","sail","or,"], sp: [false,true,true,true,true,true,true,false] },
    { syl: ["To","sail","this","schip","of","mine?”"], sp: [false,true,true,true,true,true] },
    { syl: ["Up","and","spak","an","el","dern","knicht,"], sp: [false,true,true,true,true,false,true] },
    { syl: ["Sat","at","the","kings","richt","kne:"], sp: [false,true,true,true,true,true] },
    { syl: ["“Sir","Pat","rick","Spens","is","the","best","sail","or,"], sp: [false,true,false,true,true,true,true,true,false] },
    { syl: ["That","sails","up","on","the","se.”"], sp: [false,true,true,false,true,true] }
  ] },
  { id: "cm", poet: "Dickinson", src: "Because I could not stop for Death", lines: [
    { syl: ["Be","cause","I","could","not","stop","for","Death –"], sp: [false,false,true,true,true,true,true,true] },
    { syl: ["He","kind","ly","stopped","for","me –"], sp: [false,true,false,true,true,true] },
    { syl: ["The","Car","riage","held","but","just","Our","selves –"], sp: [false,true,false,true,true,true,true,false] },
    { syl: ["And","Im","mor","tal","i","ty."], sp: [false,true,false,false,false,false] },
    { syl: ["We","slow","ly","drove –","He","knew","no","haste"], sp: [false,true,false,true,true,true,true,true] },
    { syl: ["And","I","had","put","a","way"], sp: [false,true,true,true,true,false] },
    { syl: ["My","la","bor","and","my","lei","sure","too,"], sp: [false,true,false,true,true,true,false,true] },
    { syl: ["For","His","Ci","vil","i","ty –"], sp: [false,true,true,false,false,false] }
  ] },
  { id: "browning", poet: "Browning", src: "My Last Duchess", lines: [
    { syl: ["That’s","my","last","Duch","ess","paint","ed","on","the","wall,"], sp: [false,true,true,true,false,true,false,true,true,true] },
    { syl: ["Look","ing","as","if","she","were","a","live.","I","call"], sp: [false,false,true,true,true,true,true,false,true,true] },
    { syl: ["That","piece","a","won","der,","now:","Frà","Pan","dolf’s","hands"], sp: [false,true,true,true,false,true,true,true,false,true] },
    { syl: ["Worked","bus","i","ly","a","day,","and","there","she","stands."], sp: [false,true,false,false,true,true,true,true,true,true] },
    { syl: ["Will’t","please","you","sit","and","look","at","her?","I","said"], sp: [false,true,true,true,true,true,true,true,true,true] },
    { syl: ["“Frà","Pan","dolf”","by","de","sign,","for","nev","er","read"], sp: [false,true,false,true,true,false,true,true,false,true] },
    { syl: ["Stran","gers","like","you","that","pic","tured","coun","te","nance,"], sp: [false,false,true,true,true,true,false,true,false,false] },
    { syl: ["The","depth","and","pas","sion","of","its","ear","nest","glance,"], sp: [false,true,true,true,false,true,true,true,false,true] },
    { syl: ["But","to","my","self","they","turned","(since","none","puts","by"], sp: [false,true,true,false,true,true,true,true,true,true] },
    { syl: ["The","cur","tain","I","have","drawn","for","you,","but","I)…"], sp: [false,true,false,true,true,true,true,true,true,true] }
  ] },
  { id: "pet2", poet: "Rossetti", src: "Remember", lines: [
    { syl: ["Re","mem","ber","me","when","I","am","gone","a","way,"], sp: [false,false,false,true,true,true,true,true,true,false] },
    { syl: ["Gone","far","a","way","in","to","the","si","lent","land;"], sp: [false,true,true,false,true,false,true,true,false,true] },
    { syl: ["When","you","can","no","more","hold","me","by","the","hand,"], sp: [false,true,true,true,true,true,true,true,true,true] },
    { syl: ["Nor","I","half","turn","to","go","yet","turn","ing","stay."], sp: [false,true,true,true,true,true,true,true,false,true] },
    { syl: ["Re","mem","ber","me","when","no","more","day","by","day"], sp: [false,false,false,true,true,true,true,true,true,true] },
    { syl: ["You","tell","me","of","our","fu","ture","that","you","plann’d:"], sp: [false,true,true,true,true,true,false,true,true,true] },
    { syl: ["On","ly","re","mem","ber","me;","you","un","der","stand"], sp: [false,false,true,false,false,true,true,true,false,false] },
    { syl: ["It","will","be","late","to","coun","sel","then","or","pray."], sp: [false,true,true,true,true,true,false,true,true,true] },
    { syl: ["Yet","if","you","should","for","get","me","for","a","while"], sp: [false,true,true,true,true,false,true,true,true,true] },
    { syl: ["And","af","ter","wards","re","mem","ber,","do","not","grieve:"], sp: [false,true,false,false,true,false,false,true,true,true] },
    { syl: ["For","if","the","dark","ness","and","cor","rup","tion","leave"], sp: [false,true,true,true,false,true,true,false,false,true] },
    { syl: ["A","ves","tige","of","the","thoughts","that","once","I","had,"], sp: [false,true,false,true,true,true,true,true,true,true] },
    { syl: ["Bet","ter","by","far","you","should","for","get","and","smile"], sp: [false,false,true,true,true,true,true,false,true,true] },
    { syl: ["Than","that","you","should","re","mem","ber","and","be","sad."], sp: [false,true,true,true,true,false,false,true,true,true] }
  ] },
  { id: "vill", poet: "Robinson", src: "The House on the Hill", lines: [
    { syl: ["They","are","all","gone","a","way,"], sp: [false,true,true,true,true,false] },
    { syl: ["The","House","is","shut","and","still,"], sp: [false,true,true,true,true,true] },
    { syl: ["There","is","noth","ing","more","to","say."], sp: [false,true,true,false,true,true,true] },
    { syl: ["Through","bro","ken","walls","and","gray"], sp: [false,true,false,true,true,true] },
    { syl: ["The","winds","blow","bleak","and","shrill:"], sp: [false,true,true,true,true,true] },
    { syl: ["They","are","all","gone","a","way."], sp: [false,true,true,true,true,false] },
    { syl: ["Nor","is","there","one","to-","day"], sp: [false,true,true,true,true,false] },
    { syl: ["To","speak","them","good","or","ill:"], sp: [false,true,true,true,true,true] },
    { syl: ["There","is","noth","ing","more","to","say."], sp: [false,true,true,false,true,true,true] },
    { syl: ["Why","is","it","then","we","stray"], sp: [false,true,true,true,true,true] },
    { syl: ["A","round","the","sunk","en","sill?"], sp: [false,false,true,true,false,true] },
    { syl: ["They","are","all","gone","a","way,"], sp: [false,true,true,true,true,false] },
    { syl: ["And","our","poor","fan","cy-","play"], sp: [false,true,true,true,false,true] },
    { syl: ["For","them","is","wast","ed","skill:"], sp: [false,true,true,true,false,true] },
    { syl: ["There","is","noth","ing","more","to","say."], sp: [false,true,true,false,true,true,true] },
    { syl: ["There","is","ru","in","and","de","cay"], sp: [false,true,true,false,true,true,false] },
    { syl: ["In","the","House","on","the","Hill:"], sp: [false,true,true,true,true,true] },
    { syl: ["They","are","all","gone","a","way,"], sp: [false,true,true,true,true,false] },
    { syl: ["There","is","noth","ing","more","to","say."], sp: [false,true,true,false,true,true,true] }
  ] }
];
